### ISSUE TITLE
pr0gram plugin error

### ISSUE THREAD

**Issue by phschon** [phschon/ultrabot#18]
@00SteinsGate00 , I think your Plugin behaves not as intended. When using commands like `!pr0 epic_mount` the bot does not yield any output on a discord channel.

On the console the following error is displayed:
```Task exception was never retrieved future: <Task finished coro=<pr0gramm.execute() done, defined at /home/elazar/discordbot/plugins/image_post.py:31> exception=IndexError('list index out of range',)> Traceback (most recent call last): File "/home/elazar/discordbot/plugins/image_post.py", line 33, in execute random_item = self._getRandomItem(command) File "/home/elazar/discordbot/plugins/image_post.py", line 63, in _getRandomItem return items[random.randint(0, len(items))] IndexError: list index out of range```

**Comment by j-holub** [comment]
Okay I'll look into it
