### ISSUE TITLE
Create a module system

### ISSUE THREAD

**Issue by strangeglyph** [phschon/ultrabot#2]
As noted by @00SteinsGate00 in #1, a module system which is able to load arbitrary modules from a module directory would be *noice*.

Suggested architecture: 
* Create a generic baseclass for plugins. Not sure on python best practices, but as far as I understand it, you define all methods you want and just throw `NotImplementedError`s. We probably need
  * `prefix()` - the prefix part of the command. E.g. 'swag' or 'random'
  * `help()` - return a help message
  * `execute(args)` - execute a command where args are the parameters excluding the prefix, e.g. '2d6'

* At startup, scan all files in `modules/` for python files. For each matching file, load it dynamically. See [here](https://copyninja.info/blog/dynamic-module-loading.html) for sample code

* On each module loaded that way, call some predefined method (e.g. `initialize()`) which should return an object implementing the ABC from above

* The plugin can then be registered internally

**Comment by j-holub** [comment]
That's pretty much exactly what I advised @phschon to do :D

I also vote a very base class. Indeed `NotImplementedError` is a way to do it, but I think there's a better way. `NotImplementedError` will only fail at run time, if we use the following it will (also at runtime) fail as soon as on instantiates an object that does not override all the methods.

```
rom abc import ABCMeta, abstractmethod

class UltraBotBaseModule(metalcass=ABCmeta):

    @abstractmethod
    def command():
        pass
    
    @abstractmethod
    def help():
        pass

    @abstractmethod
    def execute(args):
        pass
```

And I totally agree with everything else you said

**Comment by phschon** [comment]
Module loader was already WIP - finished now. The rest was added to the TODO-List.

**Comment by j-holub** [comment]
Yes but the way it is implemented now is not very robust, a baseclass would be better, especially for future contributors creating modules. At this stage of the project it's not yet a lot of work to create a proper module API I'd say :)

**Comment by j-holub** [comment]
Basically it would work exactly the way you do it at the moment. But right now you are assuming, that any module has a method called `execute()` and so on. Using a baseclass would not only guarantee it has that method, but it could also be used for redundant tasks.

Maybe in the future there will be something every module has to be able to do? With a baseclass it's one class you have to change, without it's all modules.

Basically like this

```
from abc import ABCMeta, abstractmethod

class UltraBotBaseModule(metalcass=ABCmeta):

    @abstractmethod
    def help(self):
        pass

    @abstractmethod
    def execute(self, command, message):
        pass
```

and the module does

```
class awesomeUBModule(UltraBotBaseModule):
     def help(self):
         print("I'm an awesome module")

    def execute(self, command, message):
         // awesome stuff
```

Not much to add actually :)
