### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by j-holub** [phschon/ultrabot#21]
Especially now since the new methods have been added I think we need some more documentation.

I tried to figure out how to use the event system and I couldn't, the code is just a bunch of methods with no comments

<img width="765" alt="bildschirmfoto 2018-03-15 um 13 34 57" src="https://user-images.githubusercontent.com/19982919/37463497-ae62019a-2855-11e8-8075-86f49f5716fe.png">

I have no idea what I have to do actually.

Furthermore I think we should document the base class and what the methods are for. I know there is an example template but it's better to have some proper documentation. Plus the template does **not** call the super constructor which is very very bad practice in my opinion.

**Comment by phschon** [comment]
I plan on adding documentation to the readme, but code documentation should be up to @Boreeas
